eureka:
  client:
    servce-url:
     defaultZone: http://localhost:8761 /eureka/
spring:
  name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/SpringCold_Sell?characterEncoding=utf-8
  jpa:
    show-sql: true