spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SomeDargon/config-repo.git
          username: 296569845@qq.com
          password: liaoxiaolong@123
          basedir: E:\workspace\basedir
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: localhost
eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
